#!/bin/sh

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'
# Begin the endless array.
echo '['
# We send an empty first array of blocks to make the loop simpler:
# echo '[],'
# Now send blocks with information forever:
case $(hostname) in
  "annoyance")
    conf=conkyrc_annoyance
    ;;
  "silence")
    conf=conkyrc_silence
    ;;
  *)
    conf=conkyrc
    ;;
esac

exec conky -c $HOME/.config/i3/$conf
